<?php  $this->getSkinUrl('css/vivacity_tweets.css'); ?>
<?php  $this->getSkinUrl('css/font-awesome.css'); ?>
<?php  $this->getSkinUrl('css/font-awesome.min.css'); ?>
<?php if($this->isEnabled() && $tweets = $this->getLateTweets()): ?>
<div class="block latest-twitter-block">
	<div class="block-title">
        <strong>
            <span><i class="fa fa-twitter"></i>&nbsp;Our Latest Tweets</span>
        </strong>
    </div>
    <div class="block-content">
    <ul>
    <?php foreach($tweets as $tweet): ?>
        <li>
<p>
<img src="<?php echo $tweet['user_image']; ?>" class="user-avatar" alt="Vivacity Infotech" height="32" width="32" align="left">
<span style="float:left;padding-left:5px;"><?php echo (string) trim($tweet["user_name"]); ?><br/><?php echo $tweet["screen_name"]; ?></span></p>
<p style="clear:both;padding-top:2px;">
				<?php echo (string) trim($tweet["tweet"]); ?></p>
                                <?php   if(isset($tweet["url"]) && !empty($tweet["url"])){ ?>
                                <img src="<?php echo $tweet["url"] ?>" >
                                <?php } ?>
				<span class="tweetSeprator"> - <?php echo (string) trim($tweet["time"]); ?></span>
            	</li>
        <?php endforeach; ?>
</ul>
    
<?php if($this->showFollowButton()): ?>
            <div class="actions footerVivatweets">		
            	<a href="https://twitter.com/<?php echo $this->getTwitterId() ?>" class="twitter-follow-button" data-show-count="false">Follow @<?php echo $this->getTwitterId() ?></a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </div>
        <?php endif; ?>
</div>
</div>
<?php endif; ?>
